apiVersion: v1
kind: Service
metadata:
  labels:
    app: camunda-server
  name: camunda-server-nodeport-service
  namespace: camunda
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: np-8080-to-8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: np-9404-to-9404-tcp
    port: 9404
    protocol: TCP
    targetPort: 9404
  - name: np-8000-to-8000-tcp
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: camunda-server
  sessionAffinity: None
  type: NodePort
